### ISSUE TITLE
Desglosar la columna de Total CP en la tabla de resumen

### ISSUE THREAD

**Issue by blackskull90** [jasp402/cypress-cucumber-report-features#1]
**Is your feature request related to a problem? Please describe.**
La solicitud no esta relacionado a un problema. Sin embargo, podría ayudar a tener mas detalle sobre la información

**Describe the solution you'd like**
Sobre la opción de la tabla resumen se podría desglosar en varias columnas como : CP activos, CP comentados, CP con Skip, CP outline = Total CP

**Comment by jasp402** [comment]
En la version 1.0.16 ya se desglosa en 
**| Path | Name | Scenes | Scenes tags | Scenes Outline | Examples | Example items |**

Ten en cuenta los Escenarios con `@skip` son tags y que puede ser cualquier tags  y puede contener más de 1 tags a la vez. Ademas puede contener tags en los escenarios como en los Examples. por tanto no es correcto colocar una columna para una situacion tan particular. sin embargo es posible colocar una columna con todos los tags. 

Se trabajara para versiones futuras. de momento considero que cumple con las condiciones solicitadas
